### ISSUE TITLE
Version 2.9 Preparations

### ISSUE THREAD

**Issue by tbetcke** [bempp/bempp#195]
The new Cython interface is almost finish and should be fully done within the next couple of days. I then want to prepare the publication of a first prerelease version for 3.0 (probably with version number 2.9).

There will still be some major development going on for a full 3.0 release as it should contain FMM and fully integrated H-Matrix code, but the pre-release will support all dense BEM functionality, allow the testing of the H-Matrix code and make it possible for users to install BEM++ easily on modern Mac and Linux distros.

I suggest the following supported systems:

Mac OS 10.10
Scientific Linux 7
Ubuntu 14.04

What is the current environment for the testing servers? Which systems are tested there?
I'd like to clean up the git branches as well. I suggest the following structure:

master - Contains current release version including minor bugfixes
development - Main development branch
release/1.0
             2.0,
             etc. - Previous release versions

feature/ Header for branches that contain code in development for specific features

What do you think. Is this reasonable? The intention is that people who just clone master automatically get the current stable release.

Timo

**Comment by rorypeck** [comment]
That's great!!!

**Comment by mdavezac** [comment]
About the testing

So we are currently automatically testing on:
- Legion, a mix of Scientific Lin 5.5-5.6 and redhat... The cluster has been down recently because of some party external to UCL blew the air con. We don't have results yet since Legion was not quite working until today
- on mac 10.x, with gnu and clang compilers: Two tests fail: bempp.space and bempp.boundary_operator.

I have a VM I can bring up to test ubuntu 14.04 if needed. But this is manual for now. Nothing for a more up-to-date Scientific Linux.

I don't think we can get BEM++ to compile on Travis until they update their VMs. Too little memory for the kind of template instantiation going on here.

@tbetcke , it is possible to get the testing to update commits and pull-requests with x and check-marks on github, so one knows visually what is passing and what is not. We just have to get together and check the CI account has the right permissions.

**Comment by mdavezac** [comment]
A branching scheme, any branching scheme, would be great!

**Comment by tbetcke** [comment]
Ok. Will implement the suggested scheme :-)

**Comment by tbetcke** [comment]
Regarding the two failed tests: I made significant changes to bempp.space and bempp.boundary_operator over Christmas and will need to update the tests over the next days.

**Comment by mdavezac** [comment]
@tbetcke, is dune-foamgrid still needed?

**Comment by tbetcke** [comment]
At the moment yes. Replacing it is the next thing I am going to work on. We
will move to Alugrid and remove all Dune patches that we currently apply.
Work on this will start after the the last bits of the Cython interface are
done in the next days.

On 5 January 2015 at 15:33, mdavezac <notifications@github.com> wrote:

> @tbetcke <https://github.com/tbetcke>, is dune-foamgrid still needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/195#issuecomment-68723886>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by alastair-radcliffe** [comment]
@tbetcke In the move to Alugrid (and then presumably also any other grid manager) would it be possible to check that GeometryGrid (needed for dynamically evolving meshes) acting on the underlying Alu/foam grid etc, also works, Thanks, Alastair

**Comment by tbetcke** [comment]
Yes. Let's discuss it once we are working on it.

Timo

On 9 January 2015 at 13:00, alastair-radcliffe <notifications@github.com>
wrote:

> @tbetcke <https://github.com/tbetcke> In the move to Alugrid (and then
> presumably also any other grid manager) would it be possible to check that
> GeometryGrid (needed for dynamically evolving meshes) acting on the
> underlying Alu/foam grid etc, also works, Thanks, Alastair
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/195#issuecomment-69331225>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
