### ISSUE TITLE
Feature request: Recomputation of integral operators on deforming meshes.

### ISSUE THREAD

**Issue by alastair-radcliffe** [bempp/bempp#205]
Hi,

I'm working with integral operators defined on meshes that deform and change shape (but not simple rotations or translations) over time, while retaining their connectivity. So only the coordinates of the mesh nodes change over time.

How difficult would it be to add the functionality to allow bempp operators to be periodically recomputed once the mesh it has been defined on has changed ?

Many thanks,

Alastair

**Comment by wsmigaj** [comment]
Hi Alastair,

right now, ``Grid`` objects in BEM++ are essentially immutable -- you can't change either the coordinates or the connectivity. (That was in any case the state of affairs in version 2.0, and I believe this hasn't changed in the current development version, with which I'm less familiar.) So to implement the feature you're proposing, one would first need to allow the modification of coordinates. One reason why this has not been done before is that I'm not aware of any functions in the generic (grid-manager-independent) Dune interface that allow changing the positions of grid vertices. Do you know if that can be done?

If this problem was resolved, then one could endow ``Grid`` objects with a "version number", incremented at each change of vertex positions. ``Space`` objects would also have a version number, in the simplest case just forwarded from the underlying ``Grid``. The version numbers of test and trial spaces used to assemble the discretised weak form of a boundary operator would be stored in ``BoundaryOperator`` along with the cached weak form, and the ``weakForm()`` function would check whether these numbers match the current version numbers of the test and trial spaces -- if not, the weak form would be recalculated.

All this might be a bit brittle, though, because some objects store pointers to the discretised weak forms rather than to the original boundary operators. Such objects would obviously have no way of knowing that the grid used to construct the discretised weak form has changed.

On the whole, things are much simpler when objects are immutable! So I would be kind of in favour of keeping them this way unless there are compelling reasons for allowing them to change. In fact, could you say what the motivation for your request is -- performance improvement, simple convenience or something else?

Performance-wise, I don't think you can save that much time by taking advantage of the fact that the mesh connectivity is unchanged. The only saving I can think of is the cost of setting up the space object (if the connectivity doesn't change, the indices of global degrees of freedom don't need to be reassigned). But the DOF assignment process is usually fast compared to weak-form assembly, so the overall speed-up is likely to be modest at best. Though perhaps there are use cases where it would be more significant. Do you have such a use case?

Best regards,
Wojciech

**Comment by alastair-radcliffe** [comment]
Hi Wojciech,

Many thanks for the extensive reply.

There is a "GeometryGrid" Dune grid manager class which is designed 
exactly for the modification of coordinates / the positions of grid 
vertices (intended just for such moving grid problems).

After the recent bempp efforts to remove the dependence on FoamGrid, and 
allow the use of ANY grid manager, i have successfully got bempp to 
accept and generate integral operators on a GeometryGrid of an 
underlying FoamGrid (ie: the GeometryGrid acts as a normal grid manager 
for accessing the FoamGrid objects, whose vertex coordinates may have 
moved, the new positions being held by the GeometryGrid in the form of 
transformation functions -- everything totally invisible to the end user).

Moving/deforming boundary problems are quite common, and Dune handles 
them very well through the GeometryGrid class, with no need for version 
numbers or anything, the GeoGrids behave exactly as any other grid.

I currently use this class for the computations of the oscillations of 
small droplets under surface tension, just refreshing/rebuilding any 
system matrices built over the deforming meshes whenever i know the 
vertices will have moved.

It would be nice to add the effects of surface charge to these droplets, 
which requires the construction of boundary integral operators over the 
deforming surface to determine the charge distribution.

At the moment, the only way i can think of to get round this problem, 
which i haven't tried yet because it is so awful, is to delete the bempp 
operators (and everything else associated to them) and create new ones 
at each iteration (corresponding to a movement of mesh nodes), of which 
there may eventually be thousands ...

It would be a shame if such functionality was not available to the bempp 
user (someone might want to look in the future at slow deformations of 
objects using the integral operators of Stokes flow, for instance ...), 
and i'm convinced the GeometryGrid class would make deforming meshes as 
easy to handle in bempp as it is in dune itself ...

Many thanks,

Alastair

**Comment by wsmigaj** [comment]
Hi Alastair,

thanks for the tip about ``GeometryGrid``.

> At the moment, the only way i can think of to get round this problem, which i haven't tried yet because it is so awful, is to delete the bempp operators (and everything else associated to them) and create new ones at each iteration (corresponding to a movement of mesh nodes), of which there may eventually be thousands ...

This approach doesn't strike me as "so awful", because, as I said before, almost all the operations it involves would also be required if the ``Grid`` class was rewritten to be mutable. You still need to reassemble the matrices of all your operators, which is normally the most time-consuming operation, don't you? (Please report back if you try out this workaround and find it does in fact incur a substantial overhead.) 

You are of course also welcome to modify BEM++ so that it allows grid changes (either along the lines I sketched in my first post or in a different way). I don't do much BEM++ programming myself any more, but perhaps Timo or other developers could comment on whether they like the idea of mutable grids (and spaces, operators, grid functions etc. that need to keep track of grid changes) or not.

Best regards,
Wojciech
