### ISSUE TITLE
Inaccurate double layer operator at acute angles

### ISSUE THREAD

**Issue by c-abird** [bempp/bempp#249]
Applying the double layer operator to a constant function f(x) = 1 should result in another constant function g(x) = +/- 0.5. On meshes with acute angles, however, the error of g(x) can get pretty large even for high quadrature degrees (see attached Gmsh file and BEM++ code). Is there anything more I can do to increase the accuracy?

![Gmsh screenshot](http://amsen.ifp.tuwien.ac.at/wp-content/uploads/2015/10/wedge.png)
wedge.geo:
```
cl = 0.05;
dz = 0.07;

Point(1) = {0, 0, 0, cl};
Point(2) = {0, 1, 0, cl};
Point(3) = {1, 0, 0, cl};
Point(4) = {1, 1, 0, cl};
Point(5) = {1, 0, dz, cl};
Point(6) = {1, 1, dz, cl};

Line(1) = {1, 3};
Line(2) = {2, 4};
Line(3) = {1, 2};
Line(4) = {3, 4};
Line(5) = {1, 5};
Line(6) = {2, 6};
Line(7) = {5, 6};
Line(8) = {3, 5};
Line(9) = {4, 6};

Line Loop(10) = {1, 4, -2, -3};
Line Loop(11) = {5, 7, -6, -3};
Line Loop(12) = {1, 8, -5};
Line Loop(13) = {2, 9, -6};
Line Loop(14) = {4, 9, -7, -8};

Plane Surface(10) = {-10};
Plane Surface(11) = {11};
Plane Surface(12) = {12};
Plane Surface(13) = {-13};
Plane Surface(14) = {14};

Surface Loop(15) = {10, 11, 12, 13, 14};
Volume(1) = {15};
```

test.py:
```python
from bempp.api import *
from bempp.api.operators.boundary.laplace import double_layer

grid  = import_grid('wedge.msh')
space = function_space(grid, "P", 1)

def fun(x, normal, domain_index, result):
  result[0] = 1.0
f = GridFunction(space, fun=fun)

dlpOp  = double_layer(space, space, space)
result = GridFunction(space, coefficients = (dlpOp * f).coefficients)

export(grid_function = result, file_name = 'h.msh')
```

**Comment by tbetcke** [comment]
Dear Claas,

this is a principle problem of the underlying quadrature rule in BEM++. At
your wedge example close to the tip you have some triangles, which are
almost on top of each other, but don't share an edge, hence are not treated
via a singular integration rule and giving large error with the standard
tensor Gauss rule. To overcome this issue with the built-in quadrature in
BEM++ is difficult. The only options you have are:

- Refine the triangles close to the tip. This pushes regions with larger
error closer to the tip.
- Crank up the double regular quadrature rule for the near field. It makes
sense then to also adapt the rel.-dist setting in that rule so that only
regular triangles close to the tip are integrated with the high accuracy
rule.

Over the last two to three weeks I have written a lot of documentation (as
time permits, teaching has started again). We have also a section on the
details of the built-in quadrature rules now. You can build this
documentation by saying 'make python_documentation' in your build
directory. You need Sphinx 1.3 for this. The output will be created in
<build_dir>/doc/python/html. Once this documentation is completed it will
be integrated into the webpage and then we can officially release
everything as BEM++ 3.0 (the development branch is pretty stable now).

Best wishes

Timo

On 22 October 2015 at 10:48, Claas Abert <notifications@github.com> wrote:

> Applying the double layer operator to a constant function f(x) = 1 should
> result in another constant function g(x) = +/- 0.5. On meshes with acute
> angles, however, the error of g(x) can get pretty large even for high
> quadrature degrees (see attached Gmsh file and BEM++ code). Is there
> anything more I can do to increase the accuracy?
>
> [image: Gmsh screenshot]
> <https://camo.githubusercontent.com/84892c2fdc587fb5df2ef0410615cc434f89a2d5/687474703a2f2f616d73656e2e6966702e74757769656e2e61632e61742f77702d636f6e74656e742f75706c6f6164732f323031352f31302f77656467652e706e67>
> wedge.geo:
>
> cl = 0.05;
> dz = 0.07;
>
> Point(1) = {0, 0, 0, cl};
> Point(2) = {0, 1, 0, cl};
> Point(3) = {1, 0, 0, cl};
> Point(4) = {1, 1, 0, cl};
> Point(5) = {1, 0, dz, cl};
> Point(6) = {1, 1, dz, cl};
>
> Line(1) = {1, 3};
> Line(2) = {2, 4};
> Line(3) = {1, 2};
> Line(4) = {3, 4};
> Line(5) = {1, 5};
> Line(6) = {2, 6};
> Line(7) = {5, 6};
> Line(8) = {3, 5};
> Line(9) = {4, 6};
>
> Line Loop(10) = {1, 4, -2, -3};
> Line Loop(11) = {5, 7, -6, -3};
> Line Loop(12) = {1, 8, -5};
> Line Loop(13) = {2, 9, -6};
> Line Loop(14) = {4, 9, -7, -8};
>
> Plane Surface(10) = {-10};
> Plane Surface(11) = {11};
> Plane Surface(12) = {12};
> Plane Surface(13) = {-13};
> Plane Surface(14) = {14};
>
> Surface Loop(15) = {10, 11, 12, 13, 14};
> Volume(1) = {15};
>
> test.py:
>
> from bempp.api import *from bempp.api.operators.boundary.laplace import double_layer
>
> grid  = import_grid('wedge.msh')
> space = function_space(grid, "P", 1)
> def fun(x, normal, domain_index, result):
>   result[0] = 1.0
> f = GridFunction(space, fun=fun)
>
> dlpOp  = double_layer(space, space, space)
> result = GridFunction(space, coefficients = (dlpOp * f).coefficients)
>
> export(grid_function = result, file_name = 'h.msh')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/249>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by c-abird** [comment]
Hi Timo,

thanks for the detailed reply. I will try out the suggested improvements and see how this works.

Best regards, Claas
