### ISSUE TITLE
problem with parallel execution

### ISSUE THREAD

**Issue by florian98765** [bempp/bempp#256]
hello, 

we are using BEM++ for strayfield calculation of magnetic particles, using a hybrid FEM-BEM approach. I recently noticed that there are some fluctuations within the calculated results, when our code is executed in parallel. I am not exactly sure where the problem arises, but the following code also produces varying results (the mesh is the same as in  #249):

test.py:
```python
from bempp.api import *
from bempp.api.operators.boundary.sparse import identity
from bempp.api.operators.boundary.laplace import double_layer
from bempp.api.assembly import InverseSparseDiscreteBoundaryOperator
from bempp.api.common import global_parameters 
import numpy as np

parameters = global_parameters()
parameters.assembly.boundary_operator_assembly_type = "dense"    

grid  = import_grid('wedge.msh')
space = function_space(grid, "P", 1)

def fun(x, normal, domain_index, result):
  result[0] = x[0]
f = GridFunction(space, fun=fun)

idOp = identity(space, space, space, parameters=parameters).weak_form()
invIdOp = InverseSparseDiscreteBoundaryOperator(idOp)
dlp = double_layer(space, space, space, parameters=parameters).weak_form()

x = np.ones(f.coefficients.shape)
for i in range(10):
  xx = dlp * x 
  x = xx
  print "TEST: %.35g" % (np.sum(x))
```

Executing this script twice gives the following results
```
florian@florian-PC02:~/bempp_test$ python test.py 
TEST: -1.1328089985316078802668471325887367
TEST: 0.0012178705414456624141206209088750256
TEST: -1.3841592106255336934873389348465977e-06
TEST: 1.6854220644386371381671194750995722e-09
TEST: -2.2108238172986357308262037287423693e-12
TEST: 3.1198249977780381344691233917346238e-15
TEST: -4.6881909423368678193961266999673203e-18
TEST: 7.3991013510342354054536934230613029e-21
TEST: -1.2097638201401603523778791559976826e-23
TEST: 2.0268903423757849385110109808143817e-26
florian@florian-PC02:~/bempp_test$ python test.py 
TEST: -1.1328089985316078802668471325887367
TEST: 0.0012178705414456624141206209088750256
TEST: -1.384159210625533481729102121271513e-06
TEST: 1.6854220644386371381671194750995722e-09
TEST: -2.2108238172986357308262037287423693e-12
TEST: 3.1198249977780381344691233917346238e-15
TEST: -4.6881909423368693601400822097560028e-18
TEST: 7.3991013510342354054536934230613029e-21
TEST: -1.2097638201401606462514668615695596e-23
TEST: 2.0268903423757857994687874619819901e-26
```

You can see that there are some deviations in the results (see e.g. the last line). When using the "hmat" assembly mode the resulting deviations get even larger. The problem vanishes if executed on a single processor (by using e.g. "taskset -c 1 python test.py")

Can anyone reproduce this problem? maybe the problem is not directly contained within BEM++ but depends on the used LAPACK / BLAS libraries (it has to be compiled with threadsafe option).

**Comment by tbetcke** [comment]
Hi Florian,

HMat internally uses a randomized recompression algorithm. This produces errors in the order of the H-Matrix accuracy. Since the algorithm is randomized these errors will change in every run. You can disable the recompression. But this will increase the memory requirements by around a factor of 2 for most problems.

The other issue is your slightly different results on parallel dense runs. Your deviations seem very small. Typically I expect small deviations in machine precision when doing parallel runs. This is due to changing orders of adding up the results depending on the task scheduler. Since floating point arithmetic is not associative you should expect variations in different runs.

Getting stable floating point results in parallel environments is quite a nontrivial topic and few libraries guarantee this.

Best wishes

Timo
