### ISSUE TITLE
multi-layer

### ISSUE THREAD

**Issue by medoptics** [bempp/bempp#264]
I want to apply bempp for diffuse equation inside multi-layer media, How can I use bempp?

**Comment by tbetcke** [comment]
Hi,

could you repose this question to the Google BEM++ forum as it is not about
software issues but about using BEM++?
Also, please provide some more detail of your problem so that we can help
you.


On 8 March 2016 at 10:30, medoptics <notifications@github.com> wrote:

> I want to apply bempp for diffuse equation inside multi-layer media, How
> can I use bempp?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/264>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by medoptics** [comment]
OK, but please indicate the site of this forum,
thanks

**Comment by medoptics** [comment]
Hi,
I want to use bempp for DOT, and the media such as brain is multilayer,
please guide me,best regards
Ali
