### ISSUE TITLE
Installer failure on release_2.0 branch - ssl error with cmake download

### ISSUE THREAD

**Issue by rhoneyager** [bempp/bempp#286]
I am trying to build bempp 2 to try out some older code that I found. It doesn't compile against the most recent bempp release, and I'd rather not port it over since I am inexperienced with Python.

When running the installer (following the instructions at http://www.bempp.org/old_installation.html), I get an error, "Peer certificate subjectAltName does not match host, expected cmake.org, got DNS:*.kitware.com, DNS:kitware.com". It's odd, since a cursory glance of the code in the stack trace indicates that http (not https) should be used to download cmake.

I've attached a copy of my bempp_setup.cfg and bempp_setup.err files.

Any help would be appreciated.

[bempp_setup.err.txt](https://github.com/bempp/bempp/files/465716/bempp_setup.err.txt)
[bempp_setup.cfg.txt](https://github.com/bempp/bempp/files/465715/bempp_setup.cfg.txt)

**Comment by tbetcke** [comment]
Hi,

I do not have any environment anymore that would support BEM++ up to version 2 in order to test and debug any issues with it. The only recommendation I can give you is to upgrade to BEM++ version 3.

If you need help porting your code please ask over at the Google bempp groups. BEM++ has seen major improvements from version 2 to 3 and it is definitely not recommended any more to use the old version.

Best wishes

Timo
